### ISSUE TITLE
Extension gets detected

### ISSUE THREAD

**Issue by trashde** [nmanumr/quizsliver#16]
**Describe the bug**
 The Quiz Silver extension is now detected by the CUI portal. 

This doesnt let the quiz to start and an error message appears on the screen.
![2022-10-09 (8)](https://user-images.githubusercontent.com/115428434/194778221-ebc9175a-4e97-4c64-b001-8b8a9e1279ce.png)

**Comment by nmanumr** [comment]
Thanks @trashde for filling the issue. It would be great if you can follow the issue template for bugs provided. Feel free to close this issue can create new one following the template.

Also please mention what error appears and what made you think cuonline is detect the presence of the extension?

**Comment by nmanumr** [comment]
Thanks @trashde for filling the issue I need to look into how they are detecting presence of the extension and hopefully we can find a workaround.

**Comment by hamzakhalid131** [comment]
> Thanks @trashde for filling the issue I need to look into how they are detecting presence of the extension and hopefully we can find a workaround.

Is there any chance that this extension problem will get solved till Saturday or sunday? We have a hybrid Islamiat Quiz 😭

**Comment by nmanumr** [comment]
@hamzakhalid131 can't promise anything but the issue seems fixable.

**Comment by nmanumr** [comment]
Its fixed now please check out this discussion for details and feedback: https://github.com/nmanumr/quizsliver/discussions/22

**Comment by hamzakhalid131** [comment]
Sorry to say but you should check this extension after update before making
it public .. I've used this extension a while ago and you won't imagine
what happened .. I totally got 8 questions on my portal Q#1 Q#2 Q#4 Q#7 Q#8
Q#11 Q#13 Q#15 .. it means due to this extension I got only 8 questions to
solve and at the end I got Q#15 and quiz ended !! More than 5 minutes were
remaining too & moreover 3 questions answers were not found .. so I request
you to plz look into it again & don't ruin other's quizes due to this ..

**Comment by ossamamehmood** [comment]
@hamzakhalid131 , We apologize but you already added the concern on #23 wait till anyone else reports a similar problem so we'll come up with a Solution. Thank You
